import os
import sys
from datetime import datetime

if __name__ == "__main__":  # pragma: no cover
    sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from sources.tools.tools import Tools


class MarkdownReport(Tools):
    """
    Create or overwrite a structured Markdown report file.

    Tool block format:
    ```markdown_report
    path=reports/my_report.md
    title=Report Title
    content=...markdown content...
    ```

    The tool will automatically add:
    - A header with the title
    - A timestamp
    - Proper markdown structure
    """

    def __init__(self):
        super().__init__()
        self.tag = "markdown_report"
        self.name = "Markdown Report"
        self.description = "Create a structured Markdown report file. Parameters: path=..., title=..., content=..."

    def _safe_target_path(self, requested_path: str) -> str:
        if requested_path is None or str(requested_path).strip() == "":
            raise ValueError("Missing required parameter: path")
        work_dir_abs = os.path.abspath(self.work_dir)
        p = str(requested_path).replace("\\", os.sep).replace("/", os.sep)
        p = p.lstrip(os.sep)
        # Ensure .md extension
        if not p.lower().endswith(".md"):
            p = p + ".md"
        target_path = os.path.abspath(os.path.join(work_dir_abs, p))
        if os.path.commonpath([work_dir_abs, target_path]) != work_dir_abs:
            raise ValueError(f"Refusing to write outside work_dir. path={requested_path}")
        return target_path

    def execute(self, blocks: list, safety: bool = False) -> str:
        if not blocks:
            return "Error: No markdown_report blocks provided."

        results = []
        for block in blocks:
            try:
                path = self.get_parameter_value(block, "path")
                title = self.get_parameter_value(block, "title") or "Report"
                content = self.get_parameter_value(block, "content")
                if content is None:
                    # Allow "text=" as alias
                    content = self.get_parameter_value(block, "text")
                if content is None:
                    raise ValueError("Missing required parameter: content")

                target = self._safe_target_path(path)
                os.makedirs(os.path.dirname(target), exist_ok=True)

                # Build the report
                timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                report_content = f"""# {title}

*Generated: {timestamp}*

---

{content.strip()}

---
*Report generated by AgenticSeek*
"""

                with open(target, "w", encoding="utf-8") as f:
                    f.write(report_content)

                results.append(f"Created markdown report: {target} ({len(report_content)} chars)")
            except Exception as e:
                return f"Error: markdown_report failed: {type(e).__name__}: {str(e)}"
        return "\n".join(results)

    def execution_failure_check(self, output: str) -> bool:
        return output is None or str(output).startswith("Error:")

    def interpreter_feedback(self, output: str) -> str:
        if self.execution_failure_check(output):
            return f"[failure] {output}"
        return f"[success] {output}"
